### ISSUE TITLE
Adding README

### ISSUE THREAD

**Issue by glihm** [cartridge-gg/cairo-proof-parser#1]
Awesome work @ThePinion! :rocket:

Would it be possible to add a brief README to guide the reader through the code?
Even if very simple. The idea is to quickly understand how this piece of software can be connected and it's scope.

Some example of questions one would have:
1. Where can I generate the proof or which format is expected.
2. What's the output of the parser.

Thank you! :pray:

**Comment by piniom** [comment]
Thanks @glihm !
Yes, absolutely. I was planning on adding the very much needed REDME but got distracted :))). It's now done, is it acceptable?

**Comment by glihm** [comment]
Awesome! That's great. :fire:
